version: "3"
services:
  tizenenv:
    build: ../../docker/tizen-env/
    container_name: tizenenv
    volumes:
      - ../../log/tizen/:/log/tizen/         
    environment:
      TZ: "Asia/Seoul"      
    restart: always
    